# These are supported funding model platforms

github: mathewlewallen
patreon: 
open_collective: 
ko_fi: 
liberapay: 
issuehunt: 
lfx_crowdfunding: 
polar: 
buy_me_a_coffee: mathewlewallen
thanks_dev: 
