# These are supported funding model platforms

github: mathewlewallen
patreon: MathewLewallen
open_collective: mathewlewallen
ko_fi: mathewlewallen
liberapay: mathewlewallen
issuehunt: mathewlewallen
lfx_crowdfunding: mathewlewallen
polar: mathewlewallen
buy_me_a_coffee: mathewlewallen
thanks_dev: mathewlewallen
